// ─── Address Resolver ────────────────────────────────────────
// Returns the correct contract addresses for any chain.
//
// Resolution order:
//   1. NEXT_PUBLIC_{PREFIX}_{CONTRACT}_ADDRESS env var
//   2. Deployment JSON file (auto‑generated by deploy script)
//   3. Hardcoded fallback map (dev convenience only)
// ─────────────────────────────────────────────────────────────

import {
  type NetworkSlug,
  NETWORK_REGISTRY,
  getDefaultChainSlug,
  networkByChainId,
} from './registry';

// ─── Types ──────────────────────────────────────────────────

export interface ContractAddresses {
  market: `0x${string}`;
  settlementVerifier: `0x${string}`;
}

const ZERO: `0x${string}` = '0x0000000000000000000000000000000000000000';

// ─── Hardcoded fallbacks (dev only — set via deploy script) ─

const FALLBACK_ADDRESSES: Partial<Record<NetworkSlug, ContractAddresses>> = {
  hardhat: {
    market: (process.env.NEXT_PUBLIC_HARDHAT_MARKET_ADDRESS as `0x${string}`) || '0x0000000000000000000000000000000000000000',
    settlementVerifier: (process.env.NEXT_PUBLIC_HARDHAT_VERIFIER_ADDRESS as `0x${string}`) || '0x0000000000000000000000000000000000000000',
  },
  sepolia: {
    market: (process.env.NEXT_PUBLIC_SEPOLIA_MARKET_ADDRESS as `0x${string}`) || '0x328882Fc63e88C4C1d7A1b3484C160De93b79c6D',
    settlementVerifier: (process.env.NEXT_PUBLIC_SEPOLIA_VERIFIER_ADDRESS as `0x${string}`) || '0xDd1Bc6a49b6c3Aced7a0b347895994f7E72d143A',
  },
};

// ─── Deployment JSON loader ─────────────────────────────────
// The deploy script writes to /public/deployments/<slug>.json
// Next.js inlines JSON imports at build time so we lazy-load.

const deploymentCache = new Map<NetworkSlug, ContractAddresses | null>();

function loadDeploymentJSON(slug: NetworkSlug): ContractAddresses | null {
  if (deploymentCache.has(slug)) return deploymentCache.get(slug)!;
  try {
    // In the browser we fetch at runtime; during SSR we skip
    if (typeof window === 'undefined') return null;
    // Attempt synchronous read from pre-loaded global (set by deploy script)
    const global_deployments = (window as unknown as Record<string, unknown>).__ZK_DEPLOYMENTS as
      | Record<string, ContractAddresses>
      | undefined;
    if (global_deployments?.[slug]) {
      deploymentCache.set(slug, global_deployments[slug]);
      return global_deployments[slug];
    }
    return null;
  } catch {
    return null;
  }
}

// ─── Env-var resolver ───────────────────────────────────────

function fromEnv(slug: NetworkSlug): ContractAddresses | null {
  const meta = NETWORK_REGISTRY[slug];
  if (!meta) return null;
  const prefix = meta.envPrefix;
  const market = process.env[`NEXT_PUBLIC_${prefix}_MARKET_ADDRESS`] as `0x${string}` | undefined;
  const verifier = process.env[`NEXT_PUBLIC_${prefix}_VERIFIER_ADDRESS`] as `0x${string}` | undefined;
  if (market && verifier) return { market, settlementVerifier: verifier };
  return null;
}

// ─── Public API ─────────────────────────────────────────────

/**
 * Resolve contract addresses for a given network slug.
 * Falls back through env → deployment JSON → hardcoded defaults.
 */
export function getAddresses(slug?: NetworkSlug): ContractAddresses {
  const target = slug ?? getDefaultChainSlug();

  // 1. Env vars (highest priority — allows runtime overrides)
  const env = fromEnv(target);
  if (env) return env;

  // 2. Deployment JSON
  const deployment = loadDeploymentJSON(target);
  if (deployment) return deployment;

  // 3. Fallback
  const fb = FALLBACK_ADDRESSES[target];
  if (fb) return fb;

  // No addresses found — return zero addresses (reads will fail gracefully)
  console.warn(`[addresses] No contract addresses found for network "${target}"`);
  return { market: ZERO, settlementVerifier: ZERO };
}

/**
 * Resolve addresses by chainId (useful in wagmi hooks).
 */
export function getAddressesByChainId(chainId: number): ContractAddresses {
  const meta = networkByChainId(chainId);
  return getAddresses(meta?.slug);
}

/**
 * Load deployment file at runtime (call once on app mount).
 * Fetches /deployments/<slug>.json and caches it.
 */
export async function loadDeployment(slug: NetworkSlug): Promise<ContractAddresses | null> {
  if (typeof window === 'undefined') return null;
  try {
    const res = await fetch(`/deployments/${slug}.json`);
    if (!res.ok) return null;
    const data = (await res.json()) as ContractAddresses;
    deploymentCache.set(slug, data);
    return data;
  } catch {
    return null;
  }
}
